// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package treasure_hunting

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestCopyResponse_Status int32

const (
	RequestCopyResponse_UNKNOWN          RequestCopyResponse_Status = 0
	RequestCopyResponse_OK               RequestCopyResponse_Status = 1
	RequestCopyResponse_I_AM_NOT_PRIMARY RequestCopyResponse_Status = 2
	RequestCopyResponse_NULL_ERROR       RequestCopyResponse_Status = 3
)

var RequestCopyResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "I_AM_NOT_PRIMARY",
	3: "NULL_ERROR",
}

var RequestCopyResponse_Status_value = map[string]int32{
	"UNKNOWN":          0,
	"OK":               1,
	"I_AM_NOT_PRIMARY": 2,
	"NULL_ERROR":       3,
}

func (x RequestCopyResponse_Status) String() string {
	return proto.EnumName(RequestCopyResponse_Status_name, int32(x))
}

func (RequestCopyResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5, 0}
}

type CopyResponse_Status int32

const (
	CopyResponse_UNKNOWN         CopyResponse_Status = 0
	CopyResponse_OK              CopyResponse_Status = 1
	CopyResponse_I_AM_NOT_BACKUP CopyResponse_Status = 2
	CopyResponse_NULL_ERROR      CopyResponse_Status = 3
)

var CopyResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "I_AM_NOT_BACKUP",
	3: "NULL_ERROR",
}

var CopyResponse_Status_value = map[string]int32{
	"UNKNOWN":         0,
	"OK":              1,
	"I_AM_NOT_BACKUP": 2,
	"NULL_ERROR":      3,
}

func (x CopyResponse_Status) String() string {
	return proto.EnumName(CopyResponse_Status_name, int32(x))
}

func (CopyResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7, 0}
}

type MoveResponse_Status int32

const (
	MoveResponse_OK                     MoveResponse_Status = 0
	MoveResponse_INVALID_INPUT          MoveResponse_Status = 1
	MoveResponse_SLOT_TAKEN             MoveResponse_Status = 2
	MoveResponse_I_AM_NOT_A_SERVER      MoveResponse_Status = 3
	MoveResponse_I_AM_ONLY_BACKUP       MoveResponse_Status = 4
	MoveResponse_SLAVE_INIT_IN_PROGRESS MoveResponse_Status = 5
)

var MoveResponse_Status_name = map[int32]string{
	0: "OK",
	1: "INVALID_INPUT",
	2: "SLOT_TAKEN",
	3: "I_AM_NOT_A_SERVER",
	4: "I_AM_ONLY_BACKUP",
	5: "SLAVE_INIT_IN_PROGRESS",
}

var MoveResponse_Status_value = map[string]int32{
	"OK":                     0,
	"INVALID_INPUT":          1,
	"SLOT_TAKEN":             2,
	"I_AM_NOT_A_SERVER":      3,
	"I_AM_ONLY_BACKUP":       4,
	"SLAVE_INIT_IN_PROGRESS": 5,
}

func (x MoveResponse_Status) String() string {
	return proto.EnumName(MoveResponse_Status_name, int32(x))
}

func (MoveResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9, 0}
}

type Coordinate struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Coordinate) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

type Slot struct {
	Treasure             bool     `protobuf:"varint,1,opt,name=treasure,proto3" json:"treasure,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (m *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(m, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetTreasure() bool {
	if m != nil {
		return m.Treasure
	}
	return false
}

func (m *Slot) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type SlotRow struct {
	Slots                []*Slot  `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotRow) Reset()         { *m = SlotRow{} }
func (m *SlotRow) String() string { return proto.CompactTextString(m) }
func (*SlotRow) ProtoMessage()    {}
func (*SlotRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *SlotRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotRow.Unmarshal(m, b)
}
func (m *SlotRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotRow.Marshal(b, m, deterministic)
}
func (m *SlotRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotRow.Merge(m, src)
}
func (m *SlotRow) XXX_Size() int {
	return xxx_messageInfo_SlotRow.Size(m)
}
func (m *SlotRow) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotRow.DiscardUnknown(m)
}

var xxx_messageInfo_SlotRow proto.InternalMessageInfo

func (m *SlotRow) GetSlots() []*Slot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type Grid struct {
	SlotRows []*SlotRow `protobuf:"bytes,1,rep,name=slot_rows,json=slotRows,proto3" json:"slot_rows,omitempty"`
	// indices for fast retrieval
	TreasureSlots        []int32          `protobuf:"varint,2,rep,packed,name=treasure_slots,json=treasureSlots,proto3" json:"treasure_slots,omitempty"`
	PlayerSlots          map[string]int32 `protobuf:"bytes,3,rep,name=player_slots,json=playerSlots,proto3" json:"player_slots,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	EmptySlots           []int32          `protobuf:"varint,4,rep,packed,name=empty_slots,json=emptySlots,proto3" json:"empty_slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (m *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(m, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetSlotRows() []*SlotRow {
	if m != nil {
		return m.SlotRows
	}
	return nil
}

func (m *Grid) GetTreasureSlots() []int32 {
	if m != nil {
		return m.TreasureSlots
	}
	return nil
}

func (m *Grid) GetPlayerSlots() map[string]int32 {
	if m != nil {
		return m.PlayerSlots
	}
	return nil
}

func (m *Grid) GetEmptySlots() []int32 {
	if m != nil {
		return m.EmptySlots
	}
	return nil
}

type RequestCopyRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCopyRequest) Reset()         { *m = RequestCopyRequest{} }
func (m *RequestCopyRequest) String() string { return proto.CompactTextString(m) }
func (*RequestCopyRequest) ProtoMessage()    {}
func (*RequestCopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *RequestCopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCopyRequest.Unmarshal(m, b)
}
func (m *RequestCopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCopyRequest.Marshal(b, m, deterministic)
}
func (m *RequestCopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCopyRequest.Merge(m, src)
}
func (m *RequestCopyRequest) XXX_Size() int {
	return xxx_messageInfo_RequestCopyRequest.Size(m)
}
func (m *RequestCopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCopyRequest proto.InternalMessageInfo

func (m *RequestCopyRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type RequestCopyResponse struct {
	Status               RequestCopyResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=treasure_hunting.RequestCopyResponse_Status" json:"status,omitempty"`
	Copy                 *CopyRequest               `protobuf:"bytes,2,opt,name=copy,proto3" json:"copy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RequestCopyResponse) Reset()         { *m = RequestCopyResponse{} }
func (m *RequestCopyResponse) String() string { return proto.CompactTextString(m) }
func (*RequestCopyResponse) ProtoMessage()    {}
func (*RequestCopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *RequestCopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCopyResponse.Unmarshal(m, b)
}
func (m *RequestCopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCopyResponse.Marshal(b, m, deterministic)
}
func (m *RequestCopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCopyResponse.Merge(m, src)
}
func (m *RequestCopyResponse) XXX_Size() int {
	return xxx_messageInfo_RequestCopyResponse.Size(m)
}
func (m *RequestCopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCopyResponse proto.InternalMessageInfo

func (m *RequestCopyResponse) GetStatus() RequestCopyResponse_Status {
	if m != nil {
		return m.Status
	}
	return RequestCopyResponse_UNKNOWN
}

func (m *RequestCopyResponse) GetCopy() *CopyRequest {
	if m != nil {
		return m.Copy
	}
	return nil
}

type CopyRequest struct {
	Grid                 *Grid          `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	PlayerStates         []*PlayerState `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
	StateVersion         int32          `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (m *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(m, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetGrid() *Grid {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *CopyRequest) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

func (m *CopyRequest) GetStateVersion() int32 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

type CopyResponse struct {
	Status               CopyResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=treasure_hunting.CopyResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CopyResponse) Reset()         { *m = CopyResponse{} }
func (m *CopyResponse) String() string { return proto.CompactTextString(m) }
func (*CopyResponse) ProtoMessage()    {}
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *CopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyResponse.Unmarshal(m, b)
}
func (m *CopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyResponse.Marshal(b, m, deterministic)
}
func (m *CopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyResponse.Merge(m, src)
}
func (m *CopyResponse) XXX_Size() int {
	return xxx_messageInfo_CopyResponse.Size(m)
}
func (m *CopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyResponse proto.InternalMessageInfo

func (m *CopyResponse) GetStatus() CopyResponse_Status {
	if m != nil {
		return m.Status
	}
	return CopyResponse_UNKNOWN
}

type MoveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Move                 int32    `protobuf:"varint,2,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{8}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveRequest) GetMove() int32 {
	if m != nil {
		return m.Move
	}
	return 0
}

type MoveResponse struct {
	Status               MoveResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=treasure_hunting.MoveResponse_Status" json:"status,omitempty"`
	PlayerStates         []*PlayerState      `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
	Copy                 *CopyRequest        `protobuf:"bytes,3,opt,name=copy,proto3" json:"copy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetStatus() MoveResponse_Status {
	if m != nil {
		return m.Status
	}
	return MoveResponse_OK
}

func (m *MoveResponse) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

func (m *MoveResponse) GetCopy() *CopyRequest {
	if m != nil {
		return m.Copy
	}
	return nil
}

type PlayerState struct {
	PlayerId             string      `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CurrentPosition      *Coordinate `protobuf:"bytes,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	Score                int32       `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{10}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerState) GetCurrentPosition() *Coordinate {
	if m != nil {
		return m.CurrentPosition
	}
	return nil
}

func (m *PlayerState) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type HeartbeatRequest struct {
	PlayerId             string    `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Registry             *Registry `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{11}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *HeartbeatRequest) GetRegistry() *Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{12}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("treasure_hunting.RequestCopyResponse_Status", RequestCopyResponse_Status_name, RequestCopyResponse_Status_value)
	proto.RegisterEnum("treasure_hunting.CopyResponse_Status", CopyResponse_Status_name, CopyResponse_Status_value)
	proto.RegisterEnum("treasure_hunting.MoveResponse_Status", MoveResponse_Status_name, MoveResponse_Status_value)
	proto.RegisterType((*Coordinate)(nil), "treasure_hunting.Coordinate")
	proto.RegisterType((*Slot)(nil), "treasure_hunting.Slot")
	proto.RegisterType((*SlotRow)(nil), "treasure_hunting.SlotRow")
	proto.RegisterType((*Grid)(nil), "treasure_hunting.Grid")
	proto.RegisterMapType((map[string]int32)(nil), "treasure_hunting.Grid.PlayerSlotsEntry")
	proto.RegisterType((*RequestCopyRequest)(nil), "treasure_hunting.RequestCopyRequest")
	proto.RegisterType((*RequestCopyResponse)(nil), "treasure_hunting.RequestCopyResponse")
	proto.RegisterType((*CopyRequest)(nil), "treasure_hunting.CopyRequest")
	proto.RegisterType((*CopyResponse)(nil), "treasure_hunting.CopyResponse")
	proto.RegisterType((*MoveRequest)(nil), "treasure_hunting.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "treasure_hunting.MoveResponse")
	proto.RegisterType((*PlayerState)(nil), "treasure_hunting.PlayerState")
	proto.RegisterType((*HeartbeatRequest)(nil), "treasure_hunting.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "treasure_hunting.HeartbeatResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xff, 0x6e, 0xe3, 0x44,
	0x10, 0x8e, 0x9d, 0xa4, 0x97, 0x8c, 0x9b, 0x9e, 0x3b, 0x3d, 0x4e, 0x25, 0xfc, 0xaa, 0xf6, 0xa8,
	0xa8, 0xd0, 0x29, 0xa2, 0x45, 0x3a, 0x10, 0x12, 0xa0, 0xb4, 0x17, 0x15, 0xd3, 0xc4, 0x89, 0x36,
	0x69, 0xd0, 0x49, 0x48, 0x96, 0x2f, 0x59, 0x05, 0xeb, 0xd2, 0x6c, 0xd8, 0xdd, 0xa4, 0x8a, 0xc4,
	0x0b, 0xf0, 0x27, 0x3c, 0x02, 0x8f, 0xc2, 0x2b, 0xf0, 0x04, 0xbc, 0x09, 0xf2, 0xae, 0x6d, 0xd2,
	0xd4, 0x17, 0xfa, 0x07, 0xff, 0xad, 0x47, 0xdf, 0x37, 0xbb, 0xf3, 0xcd, 0x37, 0x63, 0x80, 0x49,
	0x78, 0xc3, 0x1a, 0x73, 0xc1, 0x15, 0x47, 0x57, 0x09, 0x16, 0xca, 0x85, 0x60, 0xc1, 0x4f, 0x8b,
	0x99, 0x8a, 0x66, 0x93, 0x7a, 0x4d, 0x89, 0x70, 0xf4, 0x86, 0x09, 0x03, 0x20, 0x9f, 0x01, 0x5c,
	0x70, 0x2e, 0xc6, 0xd1, 0x2c, 0x54, 0x0c, 0x5d, 0x28, 0x0a, 0x7e, 0x7b, 0x68, 0x1d, 0x59, 0x27,
	0x65, 0x1a, 0x1f, 0xe3, 0xc8, 0x88, 0x4f, 0x0f, 0x6d, 0x13, 0x19, 0xf1, 0x29, 0xf9, 0x16, 0x4a,
	0xfd, 0x29, 0x57, 0x58, 0x87, 0x4a, 0x9a, 0x5c, 0x13, 0x2a, 0x34, 0xfb, 0xc6, 0xf7, 0xa0, 0x3a,
	0x9f, 0x86, 0x2b, 0x26, 0x82, 0x68, 0xac, 0xb9, 0x55, 0x5a, 0x31, 0x01, 0x6f, 0x4c, 0xbe, 0x80,
	0x47, 0x71, 0x02, 0xca, 0x6f, 0xf1, 0x39, 0x94, 0xe5, 0x94, 0x2b, 0x79, 0x68, 0x1d, 0x15, 0x4f,
	0x9c, 0xb3, 0xa7, 0x8d, 0xcd, 0xe7, 0x36, 0x34, 0xd2, 0x80, 0xc8, 0xef, 0x36, 0x94, 0x2e, 0x45,
	0x34, 0xc6, 0x17, 0x50, 0x8d, 0x23, 0x81, 0xe0, 0xb7, 0x29, 0xf5, 0xdd, 0xb7, 0x50, 0xf9, 0x2d,
	0xad, 0x48, 0x73, 0x90, 0x78, 0x0c, 0x7b, 0x19, 0xca, 0xdc, 0x6b, 0x1f, 0x15, 0x4f, 0xca, 0xb4,
	0x96, 0x46, 0x63, 0x8a, 0xc4, 0xef, 0x61, 0x37, 0x79, 0xbd, 0x01, 0x15, 0xf5, 0x0d, 0x9f, 0xdc,
	0xbf, 0x21, 0x7e, 0x4c, 0xa3, 0xa7, 0xa1, 0x9a, 0xd9, 0x9a, 0x29, 0xb1, 0xa2, 0xce, 0xfc, 0xdf,
	0x08, 0x7e, 0x04, 0x0e, 0xbb, 0x99, 0xab, 0x55, 0x92, 0xaa, 0xa4, 0xef, 0x03, 0x1d, 0xd2, 0x80,
	0xfa, 0x37, 0xe0, 0x6e, 0x66, 0x88, 0x45, 0x7f, 0xc3, 0x56, 0x5a, 0xd5, 0x2a, 0x8d, 0x8f, 0xf8,
	0x04, 0xca, 0xcb, 0x70, 0xba, 0x60, 0x49, 0x23, 0xcc, 0xc7, 0x57, 0xf6, 0x97, 0x16, 0x39, 0x05,
	0xa4, 0xec, 0xe7, 0x05, 0x93, 0xea, 0x82, 0xcf, 0x57, 0xc9, 0xf1, 0x6e, 0x03, 0xac, 0x8d, 0x06,
	0xfc, 0x65, 0xc1, 0xc1, 0x1d, 0x8e, 0x9c, 0xf3, 0x99, 0x64, 0xf8, 0x12, 0x76, 0xa4, 0x0a, 0xd5,
	0x42, 0x6a, 0xc6, 0xde, 0xd9, 0xf3, 0xfb, 0x15, 0xe7, 0xd0, 0x1a, 0x7d, 0xcd, 0xa1, 0x09, 0x17,
	0x4f, 0xa1, 0x34, 0xe2, 0xf3, 0x95, 0x7e, 0xa9, 0x73, 0xf6, 0xc1, 0xfd, 0x1c, 0x6b, 0xef, 0xa4,
	0x1a, 0x4a, 0x2e, 0x60, 0xc7, 0x24, 0x41, 0x07, 0x1e, 0x5d, 0xfb, 0x57, 0x7e, 0xf7, 0x07, 0xdf,
	0x2d, 0xe0, 0x0e, 0xd8, 0xdd, 0x2b, 0xd7, 0xc2, 0x27, 0xe0, 0x7a, 0x41, 0xb3, 0x13, 0xf8, 0xdd,
	0x41, 0xd0, 0xa3, 0x5e, 0xa7, 0x49, 0x5f, 0xb9, 0x36, 0xee, 0x01, 0xf8, 0xd7, 0xed, 0x76, 0xd0,
	0xa2, 0xb4, 0x4b, 0xdd, 0x22, 0xf9, 0xc3, 0x02, 0x67, 0x5d, 0x82, 0x4f, 0xa1, 0x34, 0x11, 0x49,
	0xf5, 0xb9, 0xd6, 0x8a, 0xbb, 0x47, 0x35, 0x06, 0xcf, 0xa1, 0x96, 0x76, 0x5c, 0x85, 0x8a, 0x19,
	0x5f, 0xe4, 0x3e, 0x3e, 0xe9, 0x55, 0x8c, 0xa2, 0x89, 0x4b, 0xf4, 0x87, 0xc4, 0x67, 0x50, 0xd3,
	0xe4, 0x60, 0xc9, 0x84, 0x8c, 0xf8, 0xec, 0xb0, 0xa8, 0x5b, 0xb5, 0xab, 0x83, 0x43, 0x13, 0x23,
	0xbf, 0x59, 0xb0, 0x7b, 0x47, 0xf3, 0xaf, 0x37, 0x34, 0x3f, 0x7e, 0x9b, 0x5e, 0xb9, 0x62, 0x93,
	0xf3, 0xed, 0xca, 0x1d, 0xc0, 0xe3, 0x4c, 0xb9, 0xf3, 0xe6, 0xc5, 0xd5, 0x75, 0x2f, 0x47, 0xb8,
	0x53, 0x70, 0x3a, 0x7c, 0xc9, 0x52, 0xdd, 0xf6, 0xc0, 0xce, 0x3c, 0x63, 0x47, 0x63, 0x44, 0x28,
	0xdd, 0xf0, 0x65, 0xea, 0x3c, 0x7d, 0x26, 0x7f, 0xda, 0xb0, 0x6b, 0x38, 0x0f, 0x2f, 0x63, 0x1d,
	0xbf, 0xe9, 0x99, 0xff, 0x43, 0xff, 0xd4, 0x77, 0xc5, 0x87, 0xfb, 0xee, 0x97, 0x4c, 0x3d, 0x23,
	0x58, 0x01, 0xf7, 0xa1, 0xe6, 0xf9, 0xc3, 0x66, 0xdb, 0x7b, 0x19, 0x78, 0x7e, 0xef, 0x7a, 0xe0,
	0x5a, 0xb1, 0x5c, 0xfd, 0x76, 0x77, 0x10, 0x0c, 0x9a, 0x57, 0x2d, 0xdf, 0xb5, 0xf1, 0x1d, 0xd8,
	0xcf, 0x34, 0x6d, 0x06, 0xfd, 0x16, 0x1d, 0xb6, 0xa8, 0x5b, 0xcc, 0x4c, 0xda, 0xf5, 0xdb, 0xaf,
	0x52, 0xad, 0x4b, 0x58, 0x87, 0xa7, 0xfd, 0x76, 0x73, 0xd8, 0x0a, 0x3c, 0xdf, 0x1b, 0x04, 0x9e,
	0x1f, 0xf4, 0x68, 0xf7, 0x92, 0xb6, 0xfa, 0x7d, 0xb7, 0x4c, 0x7e, 0xb5, 0xc0, 0x59, 0x2b, 0x67,
	0xeb, 0xcc, 0xe2, 0x25, 0xb8, 0xa3, 0x85, 0x10, 0x6c, 0xa6, 0x82, 0x39, 0x97, 0x91, 0x8a, 0x0d,
	0x66, 0x26, 0xec, 0xfd, 0xbc, 0x4a, 0xd3, 0x8d, 0x4e, 0x1f, 0x27, 0xac, 0x5e, 0x42, 0x8a, 0x37,
	0x89, 0x1c, 0x71, 0xc1, 0x12, 0x7b, 0x9a, 0x0f, 0x32, 0x01, 0xf7, 0x3b, 0x16, 0x0a, 0xf5, 0x9a,
	0x85, 0xea, 0x21, 0x3b, 0x04, 0x5f, 0x40, 0x45, 0xb0, 0x49, 0x24, 0x95, 0x48, 0x27, 0xbd, 0x9e,
	0xb7, 0x2d, 0x0c, 0x82, 0x66, 0x58, 0x72, 0x00, 0xfb, 0x6b, 0x17, 0x19, 0x37, 0x9c, 0xfd, 0x6d,
	0x83, 0x73, 0x19, 0xde, 0xb0, 0x3e, 0x13, 0xcb, 0x68, 0xc4, 0xb0, 0x03, 0x60, 0xfa, 0x12, 0xb7,
	0x0c, 0xb7, 0xb7, 0xb2, 0xfe, 0xe1, 0xf6, 0x89, 0x21, 0x05, 0xfc, 0x11, 0x9c, 0xb5, 0xbd, 0x85,
	0x1f, 0xff, 0xc7, 0x5a, 0x33, 0x69, 0x8f, 0x1f, 0xb4, 0xfc, 0x48, 0x01, 0x87, 0x50, 0xcd, 0x2a,
	0x42, 0x72, 0x9f, 0xb5, 0xa9, 0x6b, 0xfd, 0xd9, 0x56, 0x4c, 0x96, 0xb7, 0x03, 0x10, 0x8f, 0x8c,
	0x71, 0x48, 0x9e, 0x08, 0x6b, 0x43, 0x9b, 0x27, 0xc2, 0xfa, 0xbc, 0x91, 0xc2, 0xeb, 0x1d, 0xfd,
	0xbf, 0xff, 0xfc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x34, 0x25, 0x9f, 0x1e, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	StatusCopy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	RequestCopy(ctx context.Context, in *RequestCopyRequest, opts ...grpc.CallOption) (*RequestCopyResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	MovePlayer(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) StatusCopy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, "/treasure_hunting.GameService/StatusCopy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RequestCopy(ctx context.Context, in *RequestCopyRequest, opts ...grpc.CallOption) (*RequestCopyResponse, error) {
	out := new(RequestCopyResponse)
	err := c.cc.Invoke(ctx, "/treasure_hunting.GameService/RequestCopy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/treasure_hunting.GameService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) MovePlayer(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/treasure_hunting.GameService/MovePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	StatusCopy(context.Context, *CopyRequest) (*CopyResponse, error)
	RequestCopy(context.Context, *RequestCopyRequest) (*RequestCopyResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	MovePlayer(context.Context, *MoveRequest) (*MoveResponse, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) StatusCopy(ctx context.Context, req *CopyRequest) (*CopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusCopy not implemented")
}
func (*UnimplementedGameServiceServer) RequestCopy(ctx context.Context, req *RequestCopyRequest) (*RequestCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCopy not implemented")
}
func (*UnimplementedGameServiceServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (*UnimplementedGameServiceServer) MovePlayer(ctx context.Context, req *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovePlayer not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_StatusCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StatusCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treasure_hunting.GameService/StatusCopy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StatusCopy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_RequestCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).RequestCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treasure_hunting.GameService/RequestCopy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).RequestCopy(ctx, req.(*RequestCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treasure_hunting.GameService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_MovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).MovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treasure_hunting.GameService/MovePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).MovePlayer(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "treasure_hunting.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatusCopy",
			Handler:    _GameService_StatusCopy_Handler,
		},
		{
			MethodName: "RequestCopy",
			Handler:    _GameService_RequestCopy_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _GameService_Heartbeat_Handler,
		},
		{
			MethodName: "MovePlayer",
			Handler:    _GameService_MovePlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
