// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CopyResponse_Status int32

const (
	CopyResponse_UNKNOWN         CopyResponse_Status = 0
	CopyResponse_OK              CopyResponse_Status = 1
	CopyResponse_I_AM_NOT_BACKUP CopyResponse_Status = 2
	CopyResponse_NULL_ERROR      CopyResponse_Status = 3
)

var CopyResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "I_AM_NOT_BACKUP",
	3: "NULL_ERROR",
}
var CopyResponse_Status_value = map[string]int32{
	"UNKNOWN":         0,
	"OK":              1,
	"I_AM_NOT_BACKUP": 2,
	"NULL_ERROR":      3,
}

func (x CopyResponse_Status) String() string {
	return proto.EnumName(CopyResponse_Status_name, int32(x))
}
func (CopyResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{5, 0}
}

type MoveResponse_Status int32

const (
	MoveResponse_OK                     MoveResponse_Status = 0
	MoveResponse_INVALID_INPUT          MoveResponse_Status = 1
	MoveResponse_SLOT_TAKEN             MoveResponse_Status = 2
	MoveResponse_I_AM_NOT_A_SERVER      MoveResponse_Status = 3
	MoveResponse_I_AM_ONLY_BACKUP       MoveResponse_Status = 4
	MoveResponse_SLAVE_INIT_IN_PROGRESS MoveResponse_Status = 5
)

var MoveResponse_Status_name = map[int32]string{
	0: "OK",
	1: "INVALID_INPUT",
	2: "SLOT_TAKEN",
	3: "I_AM_NOT_A_SERVER",
	4: "I_AM_ONLY_BACKUP",
	5: "SLAVE_INIT_IN_PROGRESS",
}
var MoveResponse_Status_value = map[string]int32{
	"OK":                     0,
	"INVALID_INPUT":          1,
	"SLOT_TAKEN":             2,
	"I_AM_NOT_A_SERVER":      3,
	"I_AM_ONLY_BACKUP":       4,
	"SLAVE_INIT_IN_PROGRESS": 5,
}

func (x MoveResponse_Status) String() string {
	return proto.EnumName(MoveResponse_Status_name, int32(x))
}
func (MoveResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{8, 0}
}

type TakeSlotResponse_Status int32

const (
	TakeSlotResponse_OK                     TakeSlotResponse_Status = 0
	TakeSlotResponse_INVALID_INPUT          TakeSlotResponse_Status = 1
	TakeSlotResponse_SLOT_TAKEN             TakeSlotResponse_Status = 2
	TakeSlotResponse_I_AM_NOT_A_SERVER      TakeSlotResponse_Status = 3
	TakeSlotResponse_I_AM_ONLY_BACKUP       TakeSlotResponse_Status = 4
	TakeSlotResponse_SLAVE_INIT_IN_PROGRESS TakeSlotResponse_Status = 5
)

var TakeSlotResponse_Status_name = map[int32]string{
	0: "OK",
	1: "INVALID_INPUT",
	2: "SLOT_TAKEN",
	3: "I_AM_NOT_A_SERVER",
	4: "I_AM_ONLY_BACKUP",
	5: "SLAVE_INIT_IN_PROGRESS",
}
var TakeSlotResponse_Status_value = map[string]int32{
	"OK":                     0,
	"INVALID_INPUT":          1,
	"SLOT_TAKEN":             2,
	"I_AM_NOT_A_SERVER":      3,
	"I_AM_ONLY_BACKUP":       4,
	"SLAVE_INIT_IN_PROGRESS": 5,
}

func (x TakeSlotResponse_Status) String() string {
	return proto.EnumName(TakeSlotResponse_Status_name, int32(x))
}
func (TakeSlotResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{10, 0}
}

type Coordinate struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{0}
}
func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (dst *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(dst, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Coordinate) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

type Slot struct {
	Treasure             bool     `protobuf:"varint,1,opt,name=treasure,proto3" json:"treasure,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{1}
}
func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (dst *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(dst, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetTreasure() bool {
	if m != nil {
		return m.Treasure
	}
	return false
}

func (m *Slot) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type SlotRow struct {
	Slots                []*Slot  `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotRow) Reset()         { *m = SlotRow{} }
func (m *SlotRow) String() string { return proto.CompactTextString(m) }
func (*SlotRow) ProtoMessage()    {}
func (*SlotRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{2}
}
func (m *SlotRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotRow.Unmarshal(m, b)
}
func (m *SlotRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotRow.Marshal(b, m, deterministic)
}
func (dst *SlotRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotRow.Merge(dst, src)
}
func (m *SlotRow) XXX_Size() int {
	return xxx_messageInfo_SlotRow.Size(m)
}
func (m *SlotRow) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotRow.DiscardUnknown(m)
}

var xxx_messageInfo_SlotRow proto.InternalMessageInfo

func (m *SlotRow) GetSlots() []*Slot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type Grid struct {
	SlotRows []*SlotRow `protobuf:"bytes,1,rep,name=slot_rows,json=slotRows,proto3" json:"slot_rows,omitempty"`
	// indices for fast retrieval
	TreasureSlots        []int32          `protobuf:"varint,2,rep,packed,name=treasure_slots,json=treasureSlots,proto3" json:"treasure_slots,omitempty"`
	PlayerSlots          map[string]int32 `protobuf:"bytes,3,rep,name=player_slots,json=playerSlots,proto3" json:"player_slots,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	EmptySlots           []int32          `protobuf:"varint,4,rep,packed,name=empty_slots,json=emptySlots,proto3" json:"empty_slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{3}
}
func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (dst *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(dst, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetSlotRows() []*SlotRow {
	if m != nil {
		return m.SlotRows
	}
	return nil
}

func (m *Grid) GetTreasureSlots() []int32 {
	if m != nil {
		return m.TreasureSlots
	}
	return nil
}

func (m *Grid) GetPlayerSlots() map[string]int32 {
	if m != nil {
		return m.PlayerSlots
	}
	return nil
}

func (m *Grid) GetEmptySlots() []int32 {
	if m != nil {
		return m.EmptySlots
	}
	return nil
}

type CopyRequest struct {
	Grid                 *Grid    `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	StateVersion         int32    `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{4}
}
func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (dst *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(dst, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetGrid() *Grid {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *CopyRequest) GetStateVersion() int32 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

type CopyResponse struct {
	Status               CopyResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=game_pb.CopyResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CopyResponse) Reset()         { *m = CopyResponse{} }
func (m *CopyResponse) String() string { return proto.CompactTextString(m) }
func (*CopyResponse) ProtoMessage()    {}
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{5}
}
func (m *CopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyResponse.Unmarshal(m, b)
}
func (m *CopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyResponse.Marshal(b, m, deterministic)
}
func (dst *CopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyResponse.Merge(dst, src)
}
func (m *CopyResponse) XXX_Size() int {
	return xxx_messageInfo_CopyResponse.Size(m)
}
func (m *CopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyResponse proto.InternalMessageInfo

func (m *CopyResponse) GetStatus() CopyResponse_Status {
	if m != nil {
		return m.Status
	}
	return CopyResponse_UNKNOWN
}

type TakeSlotRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MoveToCoordinate     *Coordinate `protobuf:"bytes,2,opt,name=move_to_coordinate,json=moveToCoordinate,proto3" json:"move_to_coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TakeSlotRequest) Reset()         { *m = TakeSlotRequest{} }
func (m *TakeSlotRequest) String() string { return proto.CompactTextString(m) }
func (*TakeSlotRequest) ProtoMessage()    {}
func (*TakeSlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{6}
}
func (m *TakeSlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSlotRequest.Unmarshal(m, b)
}
func (m *TakeSlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSlotRequest.Marshal(b, m, deterministic)
}
func (dst *TakeSlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSlotRequest.Merge(dst, src)
}
func (m *TakeSlotRequest) XXX_Size() int {
	return xxx_messageInfo_TakeSlotRequest.Size(m)
}
func (m *TakeSlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSlotRequest proto.InternalMessageInfo

func (m *TakeSlotRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TakeSlotRequest) GetMoveToCoordinate() *Coordinate {
	if m != nil {
		return m.MoveToCoordinate
	}
	return nil
}

type MoveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Move                 string   `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{7}
}
func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (dst *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(dst, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveRequest) GetMove() string {
	if m != nil {
		return m.Move
	}
	return ""
}

type MoveResponse struct {
	Status               MoveResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=game_pb.MoveResponse_Status" json:"status,omitempty"`
	PlayerStates         []*PlayerState      `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{8}
}
func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (dst *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(dst, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetStatus() MoveResponse_Status {
	if m != nil {
		return m.Status
	}
	return MoveResponse_OK
}

func (m *MoveResponse) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

type PlayerState struct {
	PlayerId             string      `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CurrentPosition      *Coordinate `protobuf:"bytes,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	Score                int32       `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{9}
}
func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (dst *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(dst, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerState) GetCurrentPosition() *Coordinate {
	if m != nil {
		return m.CurrentPosition
	}
	return nil
}

func (m *PlayerState) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type TakeSlotResponse struct {
	Status               TakeSlotResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=game_pb.TakeSlotResponse_Status" json:"status,omitempty"`
	PlayerStates         []*PlayerState          `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TakeSlotResponse) Reset()         { *m = TakeSlotResponse{} }
func (m *TakeSlotResponse) String() string { return proto.CompactTextString(m) }
func (*TakeSlotResponse) ProtoMessage()    {}
func (*TakeSlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{10}
}
func (m *TakeSlotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSlotResponse.Unmarshal(m, b)
}
func (m *TakeSlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSlotResponse.Marshal(b, m, deterministic)
}
func (dst *TakeSlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSlotResponse.Merge(dst, src)
}
func (m *TakeSlotResponse) XXX_Size() int {
	return xxx_messageInfo_TakeSlotResponse.Size(m)
}
func (m *TakeSlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSlotResponse proto.InternalMessageInfo

func (m *TakeSlotResponse) GetStatus() TakeSlotResponse_Status {
	if m != nil {
		return m.Status
	}
	return TakeSlotResponse_OK
}

func (m *TakeSlotResponse) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

type HeartbeatRequest struct {
	PlayerId             string    `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Registry             *Registry `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{11}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (dst *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(dst, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *HeartbeatRequest) GetRegistry() *Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_275cd19293034a60, []int{12}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (dst *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(dst, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Coordinate)(nil), "game_pb.Coordinate")
	proto.RegisterType((*Slot)(nil), "game_pb.Slot")
	proto.RegisterType((*SlotRow)(nil), "game_pb.SlotRow")
	proto.RegisterType((*Grid)(nil), "game_pb.Grid")
	proto.RegisterMapType((map[string]int32)(nil), "game_pb.Grid.PlayerSlotsEntry")
	proto.RegisterType((*CopyRequest)(nil), "game_pb.CopyRequest")
	proto.RegisterType((*CopyResponse)(nil), "game_pb.CopyResponse")
	proto.RegisterType((*TakeSlotRequest)(nil), "game_pb.TakeSlotRequest")
	proto.RegisterType((*MoveRequest)(nil), "game_pb.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "game_pb.MoveResponse")
	proto.RegisterType((*PlayerState)(nil), "game_pb.PlayerState")
	proto.RegisterType((*TakeSlotResponse)(nil), "game_pb.TakeSlotResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "game_pb.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "game_pb.HeartbeatResponse")
	proto.RegisterEnum("game_pb.CopyResponse_Status", CopyResponse_Status_name, CopyResponse_Status_value)
	proto.RegisterEnum("game_pb.MoveResponse_Status", MoveResponse_Status_name, MoveResponse_Status_value)
	proto.RegisterEnum("game_pb.TakeSlotResponse_Status", TakeSlotResponse_Status_name, TakeSlotResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	TakeSlot(ctx context.Context, in *TakeSlotRequest, opts ...grpc.CallOption) (*TakeSlotResponse, error)
	StatusCopy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	MovePlayer(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) TakeSlot(ctx context.Context, in *TakeSlotRequest, opts ...grpc.CallOption) (*TakeSlotResponse, error) {
	out := new(TakeSlotResponse)
	err := c.cc.Invoke(ctx, "/game_pb.GameService/TakeSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) StatusCopy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, "/game_pb.GameService/StatusCopy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/game_pb.GameService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) MovePlayer(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/game_pb.GameService/MovePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	TakeSlot(context.Context, *TakeSlotRequest) (*TakeSlotResponse, error)
	StatusCopy(context.Context, *CopyRequest) (*CopyResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	MovePlayer(context.Context, *MoveRequest) (*MoveResponse, error)
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_TakeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).TakeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game_pb.GameService/TakeSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).TakeSlot(ctx, req.(*TakeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_StatusCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StatusCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game_pb.GameService/StatusCopy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StatusCopy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game_pb.GameService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_MovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).MovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game_pb.GameService/MovePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).MovePlayer(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game_pb.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeSlot",
			Handler:    _GameService_TakeSlot_Handler,
		},
		{
			MethodName: "StatusCopy",
			Handler:    _GameService_StatusCopy_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _GameService_Heartbeat_Handler,
		},
		{
			MethodName: "MovePlayer",
			Handler:    _GameService_MovePlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_275cd19293034a60) }

var fileDescriptor_game_275cd19293034a60 = []byte{
	// 821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x9d, 0xa4, 0x4d, 0x9e, 0x9b, 0xd6, 0x7d, 0xed, 0xa2, 0x10, 0x10, 0x94, 0x59, 0x21,
	0xf5, 0xb2, 0x11, 0x04, 0x0e, 0x0b, 0x48, 0x8b, 0xbc, 0xdd, 0xa8, 0x44, 0xcd, 0x3a, 0xd1, 0x24,
	0x29, 0xe2, 0xc2, 0xc8, 0x4d, 0x46, 0x95, 0xd5, 0x34, 0x13, 0xc6, 0x93, 0x54, 0x91, 0x38, 0xec,
	0x05, 0x89, 0x23, 0xff, 0x30, 0x12, 0x9a, 0x19, 0xdb, 0x71, 0xa3, 0x16, 0xee, 0xdc, 0xc6, 0xdf,
	0xfb, 0xde, 0x8f, 0xf9, 0xde, 0x7b, 0x63, 0x80, 0xdb, 0xe8, 0x9e, 0xb7, 0x97, 0x52, 0x28, 0x81,
	0xfb, 0xfa, 0xcc, 0x96, 0x37, 0xad, 0x86, 0x92, 0xd1, 0xf4, 0x8e, 0x4b, 0x8b, 0x93, 0xaf, 0x00,
	0x2e, 0x84, 0x90, 0xb3, 0x78, 0x11, 0x29, 0x8e, 0x3e, 0x94, 0xa5, 0x78, 0x68, 0x3a, 0x67, 0xce,
	0x79, 0x95, 0xea, 0xa3, 0x46, 0xa6, 0x62, 0xde, 0x74, 0x2d, 0x32, 0x15, 0x73, 0xf2, 0x23, 0x54,
	0x46, 0x73, 0xa1, 0xb0, 0x05, 0x35, 0x25, 0x79, 0x94, 0xac, 0x24, 0x37, 0x0e, 0x35, 0x9a, 0x7f,
	0xe3, 0x27, 0x50, 0x5f, 0xce, 0xa3, 0x0d, 0x97, 0x2c, 0x9e, 0x19, 0xdf, 0x3a, 0xad, 0x59, 0xa0,
	0x37, 0x23, 0x6d, 0xd8, 0xd7, 0x01, 0xa8, 0x78, 0xc0, 0x97, 0x50, 0x4d, 0xe6, 0x42, 0x25, 0x4d,
	0xe7, 0xac, 0x7c, 0xee, 0x75, 0x1a, 0xed, 0xb4, 0xca, 0xb6, 0x21, 0x58, 0x1b, 0xf9, 0xe0, 0x42,
	0xe5, 0x52, 0xc6, 0x33, 0x7c, 0x05, 0x75, 0x8d, 0x30, 0x29, 0x1e, 0x32, 0x0f, 0xff, 0xb1, 0x87,
	0x78, 0xa0, 0xb5, 0xc4, 0x1e, 0x12, 0xfc, 0x12, 0x0e, 0xb3, 0x82, 0x98, 0xcd, 0xe2, 0x9e, 0x95,
	0xcf, 0xab, 0xb4, 0x91, 0xa1, 0xda, 0x25, 0xc1, 0x00, 0x0e, 0xd2, 0x5a, 0x2d, 0xa9, 0x6c, 0x02,
	0x7f, 0x96, 0x07, 0xd6, 0xa9, 0xdb, 0x43, 0xc3, 0x30, 0x0e, 0xdd, 0x85, 0x92, 0x1b, 0xea, 0x2d,
	0xb7, 0x08, 0x7e, 0x0e, 0x1e, 0xbf, 0x5f, 0xaa, 0x4d, 0x1a, 0xa1, 0x62, 0xd2, 0x80, 0x81, 0x0c,
	0xa1, 0xf5, 0x06, 0xfc, 0xdd, 0x08, 0x5a, 0xd9, 0x3b, 0xbe, 0x31, 0xd2, 0xd5, 0xa9, 0x3e, 0xe2,
	0x29, 0x54, 0xd7, 0xd1, 0x7c, 0xc5, 0x53, 0xb5, 0xed, 0xc7, 0xf7, 0xee, 0x6b, 0x87, 0x4c, 0xc0,
	0xbb, 0x10, 0xcb, 0x0d, 0xe5, 0xbf, 0xad, 0x78, 0xa2, 0xf0, 0x0b, 0xa8, 0xdc, 0xca, 0x78, 0x66,
	0x7c, 0x8b, 0xaa, 0xe9, 0x52, 0xa9, 0x31, 0xe1, 0x4b, 0x68, 0x24, 0x2a, 0x52, 0x9c, 0xad, 0xb9,
	0x4c, 0x62, 0xb1, 0x48, 0x63, 0x1e, 0x18, 0xf0, 0xda, 0x62, 0xe4, 0x4f, 0x07, 0x0e, 0x6c, 0xdc,
	0x64, 0x29, 0x16, 0x09, 0xc7, 0x6f, 0x61, 0x4f, 0x13, 0x56, 0x89, 0x09, 0x7d, 0xd8, 0xf9, 0x34,
	0x0f, 0x5d, 0xa4, 0xb5, 0x47, 0x86, 0x43, 0x53, 0x2e, 0x79, 0x0b, 0x7b, 0x16, 0x41, 0x0f, 0xf6,
	0x27, 0xe1, 0x55, 0x38, 0xf8, 0x39, 0xf4, 0x4b, 0xb8, 0x07, 0xee, 0xe0, 0xca, 0x77, 0xf0, 0x04,
	0x8e, 0x7a, 0x2c, 0x78, 0xcf, 0xc2, 0xc1, 0x98, 0xbd, 0x0d, 0x2e, 0xae, 0x26, 0x43, 0xdf, 0xc5,
	0x43, 0x80, 0x70, 0xd2, 0xef, 0xb3, 0x2e, 0xa5, 0x03, 0xea, 0x97, 0xc9, 0x0c, 0x8e, 0xc6, 0xd1,
	0x9d, 0x69, 0x49, 0x76, 0xcb, 0x43, 0x70, 0xd3, 0x3b, 0xd6, 0xa9, 0x1b, 0xcf, 0x30, 0x00, 0xbc,
	0x17, 0x6b, 0xce, 0x94, 0x60, 0xd3, 0x7c, 0x64, 0xcd, 0xbd, 0xbc, 0xce, 0x49, 0xa1, 0xd0, 0xcc,
	0x44, 0x7d, 0x4d, 0x1f, 0x8b, 0x2d, 0x42, 0xbe, 0x06, 0xef, 0xbd, 0x58, 0xf3, 0xe7, 0x32, 0x20,
	0x54, 0xb4, 0x4b, 0x3a, 0xb1, 0xe6, 0x4c, 0xfe, 0x76, 0xe0, 0xc0, 0xfa, 0xfc, 0xa7, 0x46, 0x45,
	0xda, 0x8e, 0x46, 0xf8, 0x1d, 0x34, 0xb2, 0x29, 0xd3, 0x1d, 0xb0, 0xb3, 0xe8, 0x75, 0x4e, 0x73,
	0xe7, 0x74, 0x3e, 0xb4, 0x91, 0xa6, 0x03, 0x69, 0x3e, 0x12, 0xf2, 0x7b, 0x2e, 0xaf, 0x55, 0xb4,
	0x84, 0xc7, 0xd0, 0xe8, 0x85, 0xd7, 0x41, 0xbf, 0xf7, 0x8e, 0xf5, 0xc2, 0xe1, 0x64, 0xec, 0x3b,
	0x5a, 0xcf, 0x51, 0x7f, 0x30, 0x66, 0xe3, 0xe0, 0xaa, 0x1b, 0xfa, 0x2e, 0xbe, 0x80, 0xe3, 0x5c,
	0xf4, 0x80, 0x8d, 0xba, 0xf4, 0xba, 0x4b, 0xfd, 0x32, 0x9e, 0x82, 0x6f, 0xe0, 0x41, 0xd8, 0xff,
	0x25, 0x6b, 0x46, 0x05, 0x5b, 0xf0, 0xd1, 0xa8, 0x1f, 0x5c, 0x77, 0x59, 0x2f, 0xec, 0x8d, 0x59,
	0x2f, 0x64, 0x43, 0x3a, 0xb8, 0xa4, 0xdd, 0xd1, 0xc8, 0xaf, 0x92, 0x0f, 0x0e, 0x78, 0x85, 0xda,
	0x1e, 0xaf, 0xb6, 0xf3, 0x78, 0xb5, 0xf1, 0x0d, 0xf8, 0xd3, 0x95, 0x94, 0x7c, 0xa1, 0xd8, 0x52,
	0x24, 0xb1, 0xca, 0x06, 0xef, 0x99, 0x06, 0x1d, 0xa5, 0xe4, 0x61, 0xca, 0xd5, 0x1b, 0x90, 0x4c,
	0x85, 0xe4, 0xcd, 0xb2, 0xdd, 0x00, 0xf3, 0x41, 0xfe, 0x70, 0xc1, 0xdf, 0x0e, 0x47, 0xda, 0x86,
	0xd7, 0x3b, 0x6d, 0x38, 0xcb, 0x13, 0xec, 0x52, 0xff, 0x37, 0xad, 0xf8, 0x15, 0xfc, 0x9f, 0x78,
	0x24, 0xd5, 0x0d, 0x8f, 0xf2, 0x25, 0xf9, 0xd7, 0x76, 0xbc, 0x82, 0x9a, 0xe4, 0xb7, 0x71, 0xa2,
	0xe4, 0x26, 0x6d, 0xc3, 0x71, 0x7e, 0x49, 0x9a, 0x1a, 0x68, 0x4e, 0x21, 0x27, 0x70, 0x5c, 0x88,
	0x6f, 0xc5, 0xeb, 0xfc, 0xe5, 0x82, 0x77, 0x19, 0xdd, 0xf3, 0x11, 0x97, 0xeb, 0x78, 0xca, 0x31,
	0x80, 0x5a, 0x26, 0x30, 0x36, 0x9f, 0xd0, 0xdc, 0x94, 0xd5, 0xfa, 0xf8, 0xd9, 0x6e, 0x90, 0x12,
	0xfe, 0x00, 0x60, 0x55, 0xd4, 0x8f, 0x0a, 0x9e, 0xee, 0xbc, 0x31, 0x36, 0xc0, 0x8b, 0x27, 0x5f,
	0x1e, 0x52, 0xc2, 0x77, 0x50, 0xcf, 0x8b, 0xc4, 0x6d, 0x9a, 0x5d, 0x61, 0x5a, 0xad, 0xa7, 0x4c,
	0xc5, 0x12, 0xf4, 0xb6, 0xda, 0x4e, 0x17, 0x4a, 0x28, 0xbc, 0x0e, 0x85, 0x12, 0x8a, 0x8b, 0x4d,
	0x4a, 0x37, 0x7b, 0xe6, 0xd7, 0xf9, 0xcd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0xcd, 0x99,
	0x1f, 0x60, 0x07, 0x00, 0x00,
}
