// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package player_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TakeSlotResponse_Status int32

const (
	TakeSlotResponse_OK                TakeSlotResponse_Status = 0
	TakeSlotResponse_SLOT_TAKEN        TakeSlotResponse_Status = 1
	TakeSlotResponse_I_AM_NOT_A_SERVER TakeSlotResponse_Status = 2
	TakeSlotResponse_I_AM_ONLY_BACKUP  TakeSlotResponse_Status = 3
)

var TakeSlotResponse_Status_name = map[int32]string{
	0: "OK",
	1: "SLOT_TAKEN",
	2: "I_AM_NOT_A_SERVER",
	3: "I_AM_ONLY_BACKUP",
}

var TakeSlotResponse_Status_value = map[string]int32{
	"OK":                0,
	"SLOT_TAKEN":        1,
	"I_AM_NOT_A_SERVER": 2,
	"I_AM_ONLY_BACKUP":  3,
}

func (x TakeSlotResponse_Status) String() string {
	return proto.EnumName(TakeSlotResponse_Status_name, int32(x))
}

func (TakeSlotResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3, 0}
}

type Coordinate struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Coordinate) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

type TakeSlotRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MoveToCoordinate     *Coordinate `protobuf:"bytes,2,opt,name=move_to_coordinate,json=moveToCoordinate,proto3" json:"move_to_coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TakeSlotRequest) Reset()         { *m = TakeSlotRequest{} }
func (m *TakeSlotRequest) String() string { return proto.CompactTextString(m) }
func (*TakeSlotRequest) ProtoMessage()    {}
func (*TakeSlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *TakeSlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSlotRequest.Unmarshal(m, b)
}
func (m *TakeSlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSlotRequest.Marshal(b, m, deterministic)
}
func (m *TakeSlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSlotRequest.Merge(m, src)
}
func (m *TakeSlotRequest) XXX_Size() int {
	return xxx_messageInfo_TakeSlotRequest.Size(m)
}
func (m *TakeSlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSlotRequest proto.InternalMessageInfo

func (m *TakeSlotRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TakeSlotRequest) GetMoveToCoordinate() *Coordinate {
	if m != nil {
		return m.MoveToCoordinate
	}
	return nil
}

type PlayerState struct {
	PlayerId             string      `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CurrentPosition      *Coordinate `protobuf:"bytes,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	Score                int32       `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerState) GetCurrentPosition() *Coordinate {
	if m != nil {
		return m.CurrentPosition
	}
	return nil
}

func (m *PlayerState) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type TakeSlotResponse struct {
	Status               TakeSlotResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=player_proto.TakeSlotResponse_Status" json:"status,omitempty"`
	PlayerStates         []*PlayerState          `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TakeSlotResponse) Reset()         { *m = TakeSlotResponse{} }
func (m *TakeSlotResponse) String() string { return proto.CompactTextString(m) }
func (*TakeSlotResponse) ProtoMessage()    {}
func (*TakeSlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *TakeSlotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSlotResponse.Unmarshal(m, b)
}
func (m *TakeSlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSlotResponse.Marshal(b, m, deterministic)
}
func (m *TakeSlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSlotResponse.Merge(m, src)
}
func (m *TakeSlotResponse) XXX_Size() int {
	return xxx_messageInfo_TakeSlotResponse.Size(m)
}
func (m *TakeSlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSlotResponse proto.InternalMessageInfo

func (m *TakeSlotResponse) GetStatus() TakeSlotResponse_Status {
	if m != nil {
		return m.Status
	}
	return TakeSlotResponse_OK
}

func (m *TakeSlotResponse) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

type Registry struct {
	Players              []*Registry_Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Version              int32              `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Registry) Reset()         { *m = Registry{} }
func (m *Registry) String() string { return proto.CompactTextString(m) }
func (*Registry) ProtoMessage()    {}
func (*Registry) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *Registry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registry.Unmarshal(m, b)
}
func (m *Registry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registry.Marshal(b, m, deterministic)
}
func (m *Registry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registry.Merge(m, src)
}
func (m *Registry) XXX_Size() int {
	return xxx_messageInfo_Registry.Size(m)
}
func (m *Registry) XXX_DiscardUnknown() {
	xxx_messageInfo_Registry.DiscardUnknown(m)
}

var xxx_messageInfo_Registry proto.InternalMessageInfo

func (m *Registry) GetPlayers() []*Registry_Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Registry) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Registry_Player struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JoinOrder            int32    `protobuf:"varint,2,opt,name=join_order,json=joinOrder,proto3" json:"join_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registry_Player) Reset()         { *m = Registry_Player{} }
func (m *Registry_Player) String() string { return proto.CompactTextString(m) }
func (*Registry_Player) ProtoMessage()    {}
func (*Registry_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4, 0}
}

func (m *Registry_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registry_Player.Unmarshal(m, b)
}
func (m *Registry_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registry_Player.Marshal(b, m, deterministic)
}
func (m *Registry_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registry_Player.Merge(m, src)
}
func (m *Registry_Player) XXX_Size() int {
	return xxx_messageInfo_Registry_Player.Size(m)
}
func (m *Registry_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Registry_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Registry_Player proto.InternalMessageInfo

func (m *Registry_Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Registry_Player) GetJoinOrder() int32 {
	if m != nil {
		return m.JoinOrder
	}
	return 0
}

type HeartbeatRequest struct {
	PlayerId             string    `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Registry             *Registry `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{5}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *HeartbeatRequest) GetRegistry() *Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{6}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("player_proto.TakeSlotResponse_Status", TakeSlotResponse_Status_name, TakeSlotResponse_Status_value)
	proto.RegisterType((*Coordinate)(nil), "player_proto.Coordinate")
	proto.RegisterType((*TakeSlotRequest)(nil), "player_proto.TakeSlotRequest")
	proto.RegisterType((*PlayerState)(nil), "player_proto.PlayerState")
	proto.RegisterType((*TakeSlotResponse)(nil), "player_proto.TakeSlotResponse")
	proto.RegisterType((*Registry)(nil), "player_proto.Registry")
	proto.RegisterType((*Registry_Player)(nil), "player_proto.Registry.Player")
	proto.RegisterType((*HeartbeatRequest)(nil), "player_proto.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "player_proto.HeartbeatResponse")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0x52, 0x35, 0x6b, 0x4f, 0x59, 0xe7, 0x99, 0x81, 0x42, 0x51, 0x61, 0x8a, 0x84, 0xb4,
	0xab, 0x0a, 0x85, 0x8b, 0x5d, 0x81, 0x54, 0xaa, 0x22, 0xa6, 0x6e, 0x4d, 0xe5, 0x04, 0x24, 0xae,
	0xac, 0x2c, 0xb1, 0x50, 0xa0, 0xc4, 0xc5, 0x76, 0x8b, 0xf6, 0x00, 0xbc, 0x02, 0x4f, 0xc1, 0x43,
	0xf1, 0x28, 0x28, 0x8e, 0x93, 0xfe, 0xc0, 0xba, 0xbb, 0x9c, 0x2f, 0xdf, 0x77, 0xbe, 0xef, 0xf8,
	0x1c, 0x78, 0xb0, 0x98, 0xc7, 0xb7, 0x4c, 0x0c, 0x16, 0x82, 0x2b, 0x8e, 0x4d, 0x45, 0x75, 0xe5,
	0xbd, 0x04, 0x18, 0x71, 0x2e, 0xd2, 0x2c, 0x8f, 0x15, 0xc3, 0x08, 0x1a, 0x82, 0xff, 0x70, 0xad,
	0x33, 0xeb, 0xbc, 0x49, 0x8a, 0xcf, 0x02, 0x49, 0xf8, 0xdc, 0xb5, 0x4b, 0x24, 0xe1, 0x73, 0x2f,
	0x83, 0xe3, 0x28, 0xfe, 0xca, 0xc2, 0x39, 0x57, 0x84, 0x7d, 0x5f, 0x32, 0xa9, 0x70, 0x17, 0xec,
	0x2c, 0xd5, 0xaa, 0x36, 0xb1, 0xb3, 0x14, 0xbf, 0x03, 0xfc, 0x8d, 0xaf, 0x18, 0x55, 0x9c, 0x26,
	0x75, 0x73, 0xdd, 0xa3, 0xe3, 0xbb, 0x83, 0x4d, 0xff, 0xc1, 0xda, 0x9c, 0xa0, 0x42, 0x13, 0xf1,
	0x35, 0xe2, 0xfd, 0xb4, 0xa0, 0x33, 0xd3, 0xec, 0x50, 0x15, 0xf1, 0x9e, 0x42, 0xdb, 0x88, 0x6b,
	0xbb, 0x56, 0x09, 0x5c, 0xa6, 0x78, 0x04, 0x28, 0x59, 0x0a, 0xc1, 0x72, 0x45, 0x17, 0x5c, 0x66,
	0x2a, 0xe3, 0xf9, 0xbd, 0x96, 0xc7, 0x46, 0x31, 0x33, 0x02, 0x7c, 0x0a, 0x4d, 0x99, 0x70, 0xc1,
	0xdc, 0x86, 0x1e, 0xb8, 0x2c, 0xbc, 0x3f, 0x16, 0xa0, 0xf5, 0xcc, 0x72, 0xc1, 0x73, 0xc9, 0xf0,
	0x6b, 0x70, 0xa4, 0x8a, 0xd5, 0x52, 0xea, 0x24, 0x5d, 0xff, 0xc5, 0xb6, 0xcb, 0x2e, 0x7f, 0x10,
	0x6a, 0x32, 0x31, 0x22, 0xfc, 0x06, 0x8e, 0x0c, 0xbf, 0x00, 0x98, 0x74, 0xed, 0xb3, 0xc6, 0x79,
	0xc7, 0x7f, 0xb2, 0xdd, 0x65, 0x63, 0x7a, 0x62, 0x16, 0xa7, 0x0b, 0xe9, 0x5d, 0x83, 0x53, 0x76,
	0xc4, 0x0e, 0xd8, 0xc1, 0x04, 0x1d, 0xe0, 0x2e, 0x40, 0x78, 0x15, 0x44, 0x34, 0x1a, 0x4e, 0xc6,
	0x53, 0x64, 0xe1, 0x47, 0x70, 0x72, 0x49, 0x87, 0xd7, 0x74, 0x1a, 0x44, 0x74, 0x48, 0xc3, 0x31,
	0xf9, 0x38, 0x26, 0xc8, 0xc6, 0xa7, 0x80, 0x34, 0x1c, 0x4c, 0xaf, 0x3e, 0xd1, 0xb7, 0xc3, 0xd1,
	0xe4, 0xc3, 0x0c, 0x35, 0xbc, 0x5f, 0x16, 0xb4, 0x08, 0xfb, 0x9c, 0x49, 0x25, 0x6e, 0xf1, 0x05,
	0x1c, 0x96, 0x5e, 0xc5, 0x6c, 0x45, 0xaa, 0xfe, 0x76, 0xaa, 0x8a, 0x68, 0xe2, 0x91, 0x8a, 0x8d,
	0x5d, 0x38, 0x5c, 0x31, 0x21, 0xab, 0xa7, 0x6f, 0x92, 0xaa, 0xec, 0x5d, 0x80, 0x53, 0x92, 0xff,
	0x39, 0x96, 0x3e, 0xc0, 0x17, 0x9e, 0xe5, 0x94, 0x8b, 0x94, 0x09, 0x23, 0x6b, 0x17, 0x48, 0x50,
	0x00, 0x5e, 0x02, 0xe8, 0x3d, 0x8b, 0x85, 0xba, 0x61, 0x71, 0x7d, 0x6f, 0x7b, 0xef, 0xc0, 0x87,
	0x96, 0x30, 0xf9, 0xcc, 0xfe, 0x1f, 0xff, 0x3f, 0x3d, 0xa9, 0x79, 0xde, 0x43, 0x38, 0xd9, 0x30,
	0x29, 0x17, 0xe6, 0xff, 0xb6, 0xe0, 0xc8, 0xbc, 0x3f, 0x13, 0xab, 0x2c, 0x61, 0x78, 0x02, 0xad,
	0x6a, 0xad, 0xb8, 0x7f, 0xd7, 0xba, 0x75, 0xc4, 0xde, 0xb3, 0xfd, 0xd7, 0xe0, 0x1d, 0xe0, 0x29,
	0xb4, 0x6b, 0x4f, 0xbc, 0x43, 0xdf, 0x9d, 0xb8, 0xf7, 0xfc, 0xce, 0xff, 0x55, 0xbf, 0x1b, 0x47,
	0xff, 0x7a, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x77, 0xf3, 0x8d, 0xee, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerServiceClient interface {
	TakeSlot(ctx context.Context, in *TakeSlotRequest, opts ...grpc.CallOption) (*TakeSlotResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type playerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayerServiceClient(cc *grpc.ClientConn) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) TakeSlot(ctx context.Context, in *TakeSlotRequest, opts ...grpc.CallOption) (*TakeSlotResponse, error) {
	out := new(TakeSlotResponse)
	err := c.cc.Invoke(ctx, "/player_proto.PlayerService/TakeSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/player_proto.PlayerService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
type PlayerServiceServer interface {
	TakeSlot(context.Context, *TakeSlotRequest) (*TakeSlotResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedPlayerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServiceServer struct {
}

func (*UnimplementedPlayerServiceServer) TakeSlot(ctx context.Context, req *TakeSlotRequest) (*TakeSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeSlot not implemented")
}
func (*UnimplementedPlayerServiceServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}

func RegisterPlayerServiceServer(s *grpc.Server, srv PlayerServiceServer) {
	s.RegisterService(&_PlayerService_serviceDesc, srv)
}

func _PlayerService_TakeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).TakeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_proto.PlayerService/TakeSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).TakeSlot(ctx, req.(*TakeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_proto.PlayerService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player_proto.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeSlot",
			Handler:    _PlayerService_TakeSlot_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PlayerService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
